name: cizaro_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_floating_search_bar: ^0.2.6


  cupertino_icons: ^1.0.0
  provider: ^4.3.1
  shared_preferences: ^0.5.8
  flutter_svg:
  device_preview: ^0.4.8
  fluttertoast: ^7.1.6
  intl: ^0.16.1
  cached_network_image: ^2.2.0+1
  flutter_swiper: ^1.1.6
  persistent_bottom_nav_bar: ^3.1.0
  carousel_slider: ^2.3.1
  sqflite: ^1.3.2+2
  path: ^1.7.0
  google_sign_in: ^4.5.9
  flutter_facebook_auth: ^1.0.1
  flutter_screenutil: ^1.1.0
  smooth_page_indicator: ^0.2.0
  pinch_zoom_image_last: ^0.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  url_launcher: ^5.7.10
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/




  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
          style: normal

    - family: NeusaNextStd
      fonts:
        - asset: assets/fonts/NeusaNextStd-Light.otf
          weight: 600
        - asset: assets/fonts/NeusaNextStd-Bold.otf
          weight: 700
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/Segoe UI Bold.ttf
          weight: 700
        - asset: assets/fonts/Segoe UI.ttf
          weight: 100
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

